### PR TITLE
fix pygpu version for theano 1.0.1

### PR DESCRIPTION
**Pull request by guptarajat**
Fixes https://github.com/conda-forge/theano-feedstock/issues/18

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please change the build number at the top to `1`? Thanks.

**Comment by guptarajat** [comment]
Changed build to 1 @jakirkham

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks. LGTM.

**Comment by jakirkham** [comment]
Side note: It doesn't look like the email address that you committed with is associated with your GitHub account. If you [add it to GitHub]( https://help.github.com/articles/adding-an-email-address-to-your-github-account/ ) (you can have multiple emails associated with your GitHub account), it should give you credit for your contributions.

**Comment by guptarajat** [comment]
Thanks for the help @jakirkham 

When can we merge this PR? Will a new package be created automatically as this PR is merged? How long it takes for new package to become available.

**Comment by jakirkham** [comment]
> When can we merge this PR?

Once CI passes.

> Will a new package be created automatically as this PR is merged?

Yes.

> How long it takes for new package to become available.

Basically however long it takes for the CIs to build it.

Also should add that I have pulled the broken 1.0.0 and 1.0.1 packages. So they should cause less trouble.

**Comment by jakirkham** [comment]
Thanks @guptarajat. New packages should be out soon.

**Comment by guptarajat** [comment]
Thanks for note about the email :)

The idea of incrementing the build number is good. Before I started the PR, I was bit confused will it created 1.0.2 version of theano or will it just override existing 1.0.1 packages but then we lose history of things....

**Comment by jakirkham** [comment]
np.

Here's a sample name from one of the packages already uploaded `theano-1.0.1-py36_1.tar.bz2`. The build number is a package version and is independent of the actual version number.

We try not to delete packages in `conda-forge`, but instead move them to another label called `broken`. So they could be installed if someone wants to, but won't be pulled from unless a user explicitly requests to use that label in `conda`.

**Comment by guptarajat** [comment]
Things are working fine now. Thanks for the help.

**Pull request merged**
